spring.application.name=Orchestration

spring.datasource.url=jdbc:mysql://localhost:3306/DII_CLOUD
spring.datasource.username=dii
spring.datasource.password=dii_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
